import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const cocogoosePro = localFont({
  src: [
    {
      path: '../assets/fonts/cocogoose-pro.semilight.ttf',
      weight: '300',
      style: 'normal',
    }
  ],
  variable: '--font-cocogoose-pro',
  display: 'swap',
})
const mabryPro = localFont({
  src: [
    {
      path: '../assets/fonts/MabryPro-Regular.ttf',
      weight: '300',
      style: 'normal',
    }
  ],
  variable: '--font-mabry-pro',
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cocogoosePro.variable} ${mabryPro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
